# Permalinks
permalink:           pretty

# Setup
title:               Chua Yew Wee
tagline:             Data Analytics and Web Dev
url:                 https://weewey.github.io/
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Chua Yew Wee
  # url:               https://twitter.com/jamigibbs
  email:             chuayewwee@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/weewey/weewey.github.io
# google_analytics:    UA-3363703-15
# twitter:             wee
github:              weewey
facebook:            chuayw
# dribbble:            jamigibbs

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
